SCR_EditorAttributeList {
 m_aAttributes {
  Bacon_GunBuilder_ApplyLoadoutEditorAttribute "{620B262104800423}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{620B262107E414A2}" {
    Name "Loadout Editor: Apply Server Loadout"
    Description "Apply server loadout from slot number"
   }
   m_CategoryConfig "{8A757725BEAC5B36}Configs/Editor/AttributeCategories/Character.conf"
   m_Layout "{C3A25A51777A99BD}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Spinbox.layout"
   m_aAttributeDynamicDescriptions {
    Bacon_GunBuilder_ApplyLoadoutEditorAttributeDescription "{620B4136DA156C59}" {
     m_DescriptionDisplayInfo SCR_EditorAttributeUIInfo "{620B4136DC6C7363}" {
     }
    }
   }
  }
 }
}