SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{6060FB0C9F9FD498}" {
   m_sLayout "{703E00870370553E}UI/BaconLoadoutEditor/Bacon_GunBuilderUI_DialogError.layout"
   m_sTag "error"
   m_eVisualStyle WARNING
   m_sTitleIconImageName "warning"
   m_sTitle "Error"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{6060FB0CAF4C9A56}" {
     m_sTag "confirm"
     m_sActionName "DialogConfirm"
     m_sLabel "OK"
     m_eAlign RIGHT
    }
   }
  }
  SCR_ConfigurableDialogUiPreset "{6060FB1D261A9F11}" {
   m_sLayout "{703E00870370553E}UI/BaconLoadoutEditor/Bacon_GunBuilderUI_DialogError.layout"
   m_sTag "warning"
   m_sTitleIconImageName "warning"
   m_sTitle "Warning"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{6060FB0CAF4C9A56}" {
     m_sTag "confirm"
     m_sActionName "DialogConfirm"
     m_sLabel "I understand"
     m_eAlign RIGHT
    }
   }
  }
  SCR_ConfigurableDialogUiPreset "{652ED1331EEF6A9E}" {
   m_sTag "intro"
   m_eVisualStyle ACTION
   m_sTitleIconImageName "warning"
   m_sTitle "Obligatory warning"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{652ED1331EEF6A3E}" {
     m_sTag "confirm"
     m_sActionName "MenuDeleteKeybind"
     m_sLabel "I understand"
     m_eAlign RIGHT
    }
   }
  }
 }
}