MenuManager {
 MenuPresets {
  MenuPreset Bacon_GunBuilderUI {
   Layout "{725E6B7AD50A665E}UI/BaconLoadoutEditor/GunBuilder_Root.layout"
   ActionContext "Bacon_GunBuilderUI"
   Class "Bacon_GunBuilderUI"
  }
 }
}