ActionManager {
Contexts {
  ActionContext Bacon_GunBuilderUI {
   Priority 1000
   Flags 6
   Actions {
    Action PanHint {
     Curve {
      0 0
     }
     InputSource InputSourceSum "{58FE8BFED3F63F7D}" {
      Sources {
       InputSourceValue "{606A9B21429D2B7F}" {
        Input "mouse:button0"
        Filter InputFilterHold "{606A9B2148E6F192}" {
        }
       }
       InputSourceValue "{606A9B214B07504C}" {
        Input "gamepad0:right_thumb_horizontal"
       }
      }
     }
    }
    Action Panning_ModifierA {
     InputSource InputSourceSum "{6066EDA3C81F2A32}" {
      Sources {
       InputSourceValue "{6066EDA3EBA44C4F}" {
        Input "mouse:button2"
        Filter InputFilterHold "{6066EDA3F0930266}" {
         HoldDuration -1
        }
       }
       InputSourceValue "{6066EDA3FC1E1E6D}" {
        Input "gamepad0:left_trigger"
        Filter InputFilterHold "{606A9B2189448E72}" {
         HoldDuration -1
        }
       }
      }
     }
    }
    Action EditButton {
     Type Digital
     InputSource InputSourceSum "{6076E0614E353AD1}" {
      Sources {
       InputSourceValue "{6076E0615D25A4BC}" {
        Input "gamepad0:x"
        Filter InputFilterDown "{75D1A73274571C37}" {
        }
       }
       InputSourceValue "{6076E061683989CB}" {
        Input "keyboard:KC_X"
        Filter InputFilterDown "{6076E0617A098554}" {
        }
       }
      }
     }
    }
    Action ButtonSecondary {
     InputSource InputSourceSum "{6094ED240FBD1D94}" {
      Sources {
       InputSourceValue "{6076E0615D25A4BC}" {
        Input "gamepad0:x"
        Filter InputFilterDown "{75D1A73274571C37}" {
        }
       }
       InputSourceValue "{6076E061683989CB}" {
        Input "keyboard:KC_X"
        Filter InputFilterDown "{6076E0617A098554}" {
        }
       }
      }
     }
    }
    Action ButtonPrimary {
     InputSource InputSourceSum "{6094ED2496A42E6B}" {
      Sources {
       InputSourceValue "{6076E0615D25A4BC}" {
        Input "gamepad0:a"
        Filter InputFilterDown "{75D1A73274571C37}" {
        }
       }
       InputSourceValue "{6076E061683989CB}" {
        Input "keyboard:KC_RETURN"
        Filter InputFilterDown "{6076E0617A098554}" {
        }
       }
      }
     }
    }
    Action ButtonArsenalClear {
     InputSource InputSourceSum "{6094ED2394BBCF63}" {
      Sources {
       InputSourceValue "{6076E0615D25A4BC}" {
        Input "gamepad0:y"
        Filter InputFilterDown "{75D1A73274571C37}" {
        }
       }
       InputSourceValue "{6076E061683989CB}" {
        Input "keyboard:KC_DELETE"
        Filter InputFilterDown "{6076E0617A098554}" {
        }
       }
      }
     }
    }
   }
   ActionRefs {
    "Inventory_Drag"
    "Inventory_InspectPanX"
    "Inventory_InspectPanY"
    "MenuSelect"
    "MenuChange"
    "MenuBack"
    "MenuNavRight"
    "MenuNavLeft"
    "MenuUp"
    "MenuDown"
    "MenuScrollVertical"
    "MenuNavRight_NoScroll"
    "MenuNavLeft_NoScroll"
    "MenuTabLeft"
    "MenuTabRight"
    "InventoryCursorX"
    "InventoryCursorY"
   }
  }
 }
}