ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
 Actions {
  Action ATAK_Toggle {
   Type Digital
   InputSource InputSourceValue "{66CADEE3A0000002}" {
    Input "keyboard:KC_N"
    Filter InputFilterClick "{66CADEE3A0000003}" {
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "ATAK_Toggle"
   }
  }
  ActionContext ATAK_MenuContext {
   Priority 10
   Flags 0
   ActionRefs {
    "ATAK_Toggle"
   }
  }
 }
}
