SCR_KeyBindingMenuConfig : "{4EE7794C9A3F11EF}Configs/System/keyBindingMenu.conf" {
 m_KeyBindingCategories +{
  SCR_KeyBindingCategory "{66CADEE3A0000100}" {
   m_sName "ATAK"
   m_sDisplayName "ATAK Systems"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{66CADEE3A0000101}" {
     m_sActionName "ATAK_Toggle"
     m_sDisplayName "Toggle ATAK Device"
     m_sPreset "click"
    }
   }
  }
 }
}
